name: Test Build

on:
  push:

jobs:
  release:
    name: Test Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test Build
      shell: bash -l {0}
      run: |
        nvm i
        npm ci
        npm run build
        ls -R components utils
        npx pkg-size
        npm publish --dry-run
